apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: workflow-patches.yaml
  target:
    group: argoproj.io
    kind: WorkflowTemplate
    name: fibonacci-template
    version: v1alpha1
- path: service-patches.yaml
  target:
    kind: Service
    name: fast-api-service
    version: v1
images:
- name: FASTAPI_IMAGE
  newName: astin75/fast-api
  newTag: v1.0.31
namespace: production
nameSuffix: -production
