# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: 'Kustomize GitHub Actions'

on:
  push:
    branches: [ "staging" ]
    paths:
      - git_ops/kustomize_chart/fast-api/overlays/staging/**
env:
  KUSTOMIZEE_DIR: kustomize_chart/fast-api/overlays/staging/
  KUSTOMIZEE_OUTPUT_DIR: deploy/staging/deployment.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[Kustomize build]') }}
    # build job 완료 후 진행
    steps:
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Checkout kustomize repository
        uses: actions/checkout@v2
        with:
          # kubernetes 설정정보 저장소
          repository: astin75/git_ops
          ref: staging
          # 다른 저장소에 push 하려면 Personal Access Token이 필요.
          token: ${{ secrets.PERSONAL_ACCESS_TOKENS }}
      # 새 이미지 버전으로 파일 수정
      - name: Update Kubernetes resources
        run: |
          kustomize build $KUSTOMIZEE_DIR > $KUSTOMIZEE_OUTPUT_DIR

      - name: Commit files
        run: |
          git config --global user.email astin75@gmail.com
          git config --global user.name astin75           
          git add .
          git commit -m "Kustomize build"
          git push




        

