# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: 'Kustomize GitHub Actions'

on:
  push:
    branches: [ "staging" ]
env:
  KUSTOMIZEE_DIR: kustomize_chart/fast-api/overlays/production/
  KUSTOMIZEE_OUTPUT_DIR: deploy/production/deployment.yaml

jobs:
  create-deployment-branch:
    runs-on: ubuntu-latest
    needs:
      - publish-image
    steps:
      - uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: '5.0.3'
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKENS }}
      - run: |
          git switch staging
          kustomize $KUSTOMIZEE_DIR > $KUSTOMIZEE_OUTPUT_DIR
          git config --global user.email astin75@gmail.com
          git config --global user.name astin75           
          git add .
          git commit -m "Kustomize build"
          git push



        

