# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: 'Kustomize GitHub Actions'

on:
  push:
    branches: [ "staging" ]
jobs:
  kustomize:
    name: 'Kustomize'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Kustomize Build'
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: '5.0.3'
          kustomize_build_dir: 'kustomize_chart/fast-api/overlays/production/' 
          kustomize_comment: true
          kustomize_output_file: "git_ops/deploy/production/deployment.yaml"
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKENS }}
      
      - name: Commit files
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKENS }}
        run: |
          git config --global user.email astin75@gmail.com
          git config --global user.name astin75          
          git add .
          git commit -m "Kustomize build"
          git push                    

