# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: 'Production Kustomize GitHub Actions'

on:
  push:
    branches: 
      - staging
    paths:
      - deploy/staging/**.yaml
env:
  KUSTOMIZEE_DIR: kustomize_chart/fast-api/overlays/production/
  KUSTOMIZEE_OUTPUT_DIR: deploy/production/deployment.yaml


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout staging repository
      uses: actions/checkout@v2
      with:
        # kubernetes 설정정보 저장소
        repository: astin75/git_ops
        ref: staging
        # 다른 저장소에 push 하려면 Personal Access Token이 필요.
        token: ${{ secrets.PERSONAL_ACCESS_TOKENS }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
    - name: kustomize_overlay_update
      run: |
        python utils/overlay_parser.py 
        
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1

      #  kustomize build     
    - name: Update Kubernetes resources
      run: |
        kustomize build $KUSTOMIZEE_DIR > $KUSTOMIZEE_OUTPUT_DIR

    - name: Commit files
      run: |
        git config --global user.email astin75@gmail.com
        git config --global user.name astin75           
        git add .
        git commit -m "Kustomize Production build"
        git push
      
